In [ ]:
from pandas import DataFrame

In [ ]:
data = {'bids': [[0.229, 208.96], [0.2269, 493.24], [0.2268, 422.15], [0.2245, 639.69], [0.2224, 126.63], [0.2223, 5623.28], [0.2222, 861.71], [0.2207, 2000.0], [0.22, 1437.64], [0.2199, 1088.36], [0.2181, 100.0], [0.2176, 1319.77], [0.2153, 1556.12], [0.215, 458.83], [0.213, 1797.54], [0.2107, 2044.21], [0.21, 1901.23], [0.2084, 2332.47], [0.2061, 2554.01], [0.2057, 408.36], [0.205, 739.23], [0.2038, 2817.49], [0.202, 627.32], [0.2016, 3086.97], [0.201, 55.34], [0.2, 3044.73], [0.1993, 3362.64], [0.197, 3644.72], [0.196, 255.1], [0.195, 624.11], [0.1947, 3933.44], [0.194, 634.01], [0.1924, 4229.04], [0.1901, 4531.75], [0.1878, 4841.85], [0.1855, 5159.61], [0.1852, 172.78], [0.185, 538.24], [0.1832, 5485.31], [0.1809, 5819.26], [0.18, 185.8], [0.1787, 6161.76], [0.1764, 6513.17], [0.175, 1742.21], [0.1741, 6873.82], [0.1723, 200.0], [0.15, 53.33], [0.1113, 898.47], [0.11, 181.81], [0.1013, 987.16], [0.1, 1384.04], [0.054, 666.92], [0.0151, 6622.51], [0.0126, 15880.95], [0.0001, 65000.0]], 'asks': [[0.2319, 173.09], [0.2344, 467.7], [0.2345, 68.76], [0.2346, 277.83], [0.2369, 250.0], [0.237, 1356.86], [0.2392, 117.14], [0.2393, 833.5], [0.2416, 1111.34], [0.2425, 662.52], [0.244, 1389.17], [0.245, 620.0], [0.2463, 1667.01], [0.2476, 54.88], [0.2487, 1944.84], [0.25, 205.58], [0.251, 2222.68], [0.2534, 2500.51], [0.2557, 2778.35], [0.2581, 3056.18], [0.26, 337.64], [0.2604, 3334.02], [0.2628, 3611.85], [0.2645, 500.0], [0.2651, 3889.69], [0.2674, 4167.52], [0.2689, 390.44], [0.2698, 4445.36], [0.27, 1273.34], [0.2721, 4723.19], [0.2745, 5001.03], [0.275, 73.67], [0.2768, 5278.86], [0.2769, 47.43], [0.2792, 5556.69], [0.28, 1514.85], [0.2815, 5834.53], [0.2839, 6112.36], [0.2862, 6390.2], [0.2877, 720.95], [0.2886, 6668.03], [0.29, 413.18], [0.2985, 524.78], [0.2999, 828.08], [0.3, 2917.89], [0.3007, 366.68], [0.303, 213.3], [0.3051, 25.28], [0.308, 236.93], [0.3095, 100.0], [0.3168, 99.87], [0.319, 2040.0], [0.33, 231.62], [0.333, 764.77], [0.3336, 33.36], [0.334, 299.4], [0.34, 2676.86], [0.342, 100.0], [0.343, 290.62], [0.347, 7089.52], [0.348, 1594.48], [0.3499, 17.49], [0.35, 5999.79], [0.3528, 75.84], [0.3592, 675.0], [0.36, 2635.19], [0.37, 3711.63], [0.3724, 285.22], [0.376, 5597.04], [0.3763, 13.95], [0.38, 3973.67], [0.39, 66.54], [0.3994, 1000.12], [0.4, 606.43], [0.405, 12.41], [0.41, 15.0], [0.42, 15.0], [0.43, 15.0], [0.44, 17.06], [0.45, 430.0], [0.4505, 2749.72], [0.456, 1000.0], [0.46, 3117.88], [0.469, 453.0], [0.47, 4874.38], [0.48, 2393.27], [0.4828, 27.98], [0.49, 35062.52], [0.4965, 3062.4], [0.497, 124.69], [0.4987, 988.54], [0.5, 10638.67], [0.5041, 1169.34], [0.51, 196.19], [0.5989, 8.35], [0.6, 1407.99], [0.62, 9366.21], [0.6436, 610.0], [0.673, 530.0], [0.7, 380.8]]}

In [ ]:
df = DataFrame(columns=['bids_price','bids_amount'], data = data['bids'])
df_ = DataFrame(columns=['asks_price','asks_amount'], data = data['asks'])
df = df_.join(df).dropna()
df

### Libs

In [2]:
import requests
import pandas as pd
from datetime import datetime
import hmac
import hashlib

### Recent pairs

In [10]:
base_url = 'https://api.mexc.com/api/v3/'
url = f"{base_url}ticker/24hr"
res = requests.get(url)
values = res.json()
df = pd.DataFrame(values)
df = df[df.lastPrice=='0'][['symbol','askPrice','askQty']]
df

            symbol askPrice askQty
387      MINARUSDT        0      0
397       LUMIUSDT        0      0
631      PEPE3USDT        0      0
1575    DLANCEUSDT        0      0
1625     TROSSUSDT        0      0
1847  HAPPYCATUSDT        0      0

In [17]:
url = "https://api.mexc.com/api/v3/defaultSymbols"
res = requests.get(url)
values = res.json()
df = pd.DataFrame(values)

In [18]:
df

           data  code      msg      timestamp
0     GENE1USDT     0  success  1691426626625
1       SNTUSDT     0  success  1691426626625
2      CGPTUSDT     0  success  1691426626625
3     HEGICUSDT     0  success  1691426626625
4       GDCUSDT     0  success  1691426626625
...         ...   ...      ...            ...
1626    KOYUSDT     0  success  1691426626625
1627    NTPUSDT     0  success  1691426626625
1628    AZYUSDT     0  success  1691426626625
1629    MMOUSDT     0  success  1691426626625
1630   PEPAUSDT     0  success  1691426626625

[1631 rows x 4 columns]

In [23]:
df[df.data=="INSRUSDT"]

Empty DataFrame
Columns: [data, code, msg, timestamp]
Index: []

In [6]:
apiKey = ""
secretKey = "45d0b3c26f2644f19bfb98b07741b2f5"
symbol = 'PIRIUSDT'

In [42]:
timestamp = int(datetime.now().timestamp()*1000)
url = f"symbol=BTCUSDT&side=BUY&type=LIMIT&quantity=1&price=0&recvWindow=5000&timestamp={timestamp}"
signature = hmac.new(
    secretKey.encode(),
    msg=url.encode(),
    digestmod=hashlib.sha256
).hexdigest().lower()

url = f"https://api.mexc.com/api/v3/order/test?{url}&signature={signature}"
headers = {'X-MEXC-APIKEY': apiKey}
requests.post(url, headers=headers).json()

{'code': 700002, 'msg': 'Signature for this request is not valid.'}

In [1]:
print(int(datetime.now().timestamp()*1000))
server_time_url = f'{base_url}time'
res = requests.get(server_time_url)
values = res.json()
values['serverTime']

NameError: name 'datetime' is not defined

In [2]:
import mexc_spot_v3

In [3]:
hosts = "https://api.mexc.com"
mexc_key = ""
mexc_secret = "45d0b3c26f2644f19bfb98b07741b2f5"

In [5]:
capital = mexc_spot_v3.mexc_capital(mexc_key=mexc_key, mexc_secret=mexc_secret, mexc_hosts=hosts)
response = capital.get_coinlist()
print(response)

{'code': 700002, 'msg': 'Signature for this request is not valid.'}